# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Asylum
tagline:          'lonely'
description:      'A lonely talk to myself. <br/><a href="https://twitter.com/xianminx" target="_blank">@xianminx</a>.'
url:              https://xianminx.github.io
baseurl:          ''

author :
  name : Asylum
  url:   https://twitter.com/xianminx
  email : xianminx  gmail com
  github : xianminx
  twitter : xianminx

safe: true
lsi: false
source:      .
destination: ./_site
plugins_dir:     ./_plugins

google_analytics: UA-32905076-1
JEKYLL_ENV: production

maruku:
  use_tex:   false
  use_divs:  false
  png_dir:   images/latex/
  png_url:   /images/latex/
exclude:
  - README.txt
  - Rakefile


paginate:         100

# Custom vars
version:          2.0

github:
  repo:           https://github.com/xianminx/xianminx.github.com

gems: [jekyll-paginate]
