title : Lucas Xu

author :
  name : Lucas Xu
  email : xianminx  gmail com
  github : xianminx
  twitter : xianminx

url: http://xianminx.github.io/

safe: true
lsi: false
source:      .
destination: ./_site
plugins:     ./_plugins


auto:        false
server_port: 4000
pygments:    true
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
permalink:   pretty
paginate:    5
maruku:
  use_tex:   false
  use_divs:  false
  png_dir:   images/latex/
  png_url:   /images/latex/
exclude:
  - README.txt
  - Rakefile
